name: Build APK
on: [push]
jobs:
      build-android:
        name: Build for Android
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Build with Buildozer
            run: |
              sudo apt update
              sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev aidl
              pip install --user --upgrade Cython virtualenv
              pip install --user buildozer
              export PATH=$PATH:~/.local/bin/
              cd Android_PreBuild
              buildozer -v android debug
          - name: Upload artifacts
            uses: actions/upload-artifact@v2
            with:
              name: package
              path: bin/*.apk
